[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10.2.4"
  NEXT_TELEMETRY_DISABLED = "1"
  NEXT_USE_NODE_NAMESPACE = "true"

# Handle client-side routing for Next.js App Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Required for static assets
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"  # Disable caching during development

# Required for Next.js static export
[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@prisma/client", "@prisma/adapter-pg"]

[dev]
  framework = "next"
  targetPort = 3000
  port = 3000
